### ISSUE TITLE
Help strings for subconfigurables

### ISSUE THREAD

**Issue by kadrlica** [lsst/pex_config#26]
I've been trying to access the configurable options for a "nested" config like `ProcessCcdConfig` (i.e., a config that contains other `ConfigurableInstance` objects). I would have thought that something like this would work to give me the help string for an `IsrTaskConfig` object, but instead I get the help for a `ConfigurableInstance`

```
from lsst.pipe.tasks.processCcd import ProcessCcdConfig
config = ProcessCcdConfig()
help(config.isr)
```
and the output:
```
Help on ConfigurableInstance in module lsst.pex.config.configurableField object:

class ConfigurableInstance(builtins.object)
 |  Methods defined here:
...
```

This is continuing off of a Slack conversation with @jonathansick @mfisherlevine @PaulPrice

**Comment by mfisherlevine** [comment]
I think that the root of this is also what causes `help(config.<int_field>)` to return the help for an int, rather than the docstring and options for that int-field in the config. If it's somehow not, that's something to fix too...

**Comment by ktlim** [comment]
This issue has been ported to https://jira.lsstcorp.org/browse/DM-15758.  Please follow it there.

**Comment by ktlim** [comment]
Sorry, I shouldn't have closed this, in order to allow for further comments here.

**Comment by ktlim** [comment]
Could you please look at the proposed solution in the above Jira issue and PR #27?

**Comment by ktlim** [comment]
The docstring fix was just merged.  I think this is the best we can do at this time.
